version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sqls/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gerhuhaer
      MYSQL_DATABASE: todoList
      MYSQL_USER: t0w4
      MYSQL_PASSWORD: faweufhli

  sample-server:
    image: ergofriend/ogp-local-checker:prod
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always

  auth-proxy:
    build: .
    depends_on:
      - sample-server
    ports:
      - 8080:80
